### ISSUE TITLE
Cast to DLNA player

### ISSUE THREAD

**Issue by t3b4n** [leinelissen/jellyfin-audio-player#124]
Hello! I have an Onkyo receiver with DLNA capabilities. Could you add a feature to cast to these kind of devices?

**Comment by leinelissen** [comment]
Hey there! Thanks for making a suggestion. Doesn't Onkyo support Apple AirPlay?

**Comment by t3b4n** [comment]
Yes, they do, but mine is older, and Airplay wasn't available at that time. I do have an airplay receiver attached to one of the inputs of the receiver, but unfortunately it doesn't support hi-res files (while the receiver does). That's why I'm requesting that feature.

**Comment by leinelissen** [comment]
Ah okay, this makes sense. My vision for Fintunes is to leave playback as much to the OS as possible, so we can leverage native things such as background playback. As far as I know, DLNA has no native iOS nor Android support, and making a full implementation for this in the app is undesirable due to performance and UX considerations. Until DLNA has native support, I will not be implementing it in Fintunes.
