### ISSUE TITLE
Crash on iOS 13.7

### ISSUE THREAD

**Issue by yuruxuan** [leinelissen/jellyfin-audio-player#145]
Please don't build iOS archive by xcode 14.3. You can see this [Xcode 14.3: App built is not able to open on iOS 13.6](https://developer.apple.com/forums/thread/727680).

**Comment by leinelissen** [comment]
Hey there, sorry for not getting back to this earlier. This issue has been fixed in [Xcode 14.3.1 RC](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3_1-release-notes). I'll upgrade to this version and I will build the next app version with this Xcode version. I'll leave this issue open until this is the case.

**Comment by leinelissen** [comment]
v2.2.0 was just released, which has been built using Xcode 14.3.1. This should resolve the issue.
