### ISSUE TITLE
Different tracks cover

### ISSUE THREAD

**Issue by FaboThePlayer** [leinelissen/jellyfin-audio-player#153]
App puts song cover from played album, however it would be awesome if app could show different covers if song has one.

**Comment by leinelissen** [comment]
Thanks for this. It's correct that the album image is displayed when the track is part of an album. The thing I was wondering is about the use case. Are there albums of songs that have individually different album covers? I couldn't find any in my music library.

**Comment by FaboThePlayer** [comment]
For my use case I have album with various songs, different artists, different songs.

**Comment by leinelissen** [comment]
Are those commercially available albums or ones you've created yourself? Just so I'm clear there isn't a mixup between albums and playlists.

**Comment by FaboThePlayer** [comment]
Yeah I've created album by myself. Couldn't find any way to create playlist the way I create albums (importing song to folder when there is a new song available, that way the song appears in the album).

**Comment by leinelissen** [comment]
Ah right. In that case I will leave the current setup as is, because I want to ensure an album cover is in cache in case an entire album is downloaded. In the future, I need to refactor the downloading feature so that it also downloads album covers. In that case, support for individual cover images should be feasible.
