### ISSUE TITLE
Wave audio format support?

### ISSUE THREAD

**Issue by Mis1ify** [leinelissen/jellyfin-audio-player#155]
I've noticed that I can't play .wav songs. It shows up, but and I press play I see 0:00 on music player.

**Comment by wildrun0** [comment]
Same thing. It just doesn't do nothing.
<img src="https://github.com/leinelissen/jellyfin-audio-player/assets/37260144/0798048d-b8d6-4a58-8fc2-5cb2477b802c" width="264" height="572">
If i try to play .aif file, at least it shows some circular progress bar

**Comment by leinelissen** [comment]
The progress indicator is shown because it tries to transcode the format (admittedly unsuccessfully). Proper transcoding support is on the way (tracked in #97), but requires a new minor Jellyfin release.

As for both AIF and WAV, I need to do some checks with various codecs for support. I think iOS can play those files directly, but I have no direct evidence for this. Let me get back to you on this.

**Comment by leinelissen** [comment]
This should now be fixed with v2.3.0 🚀

**Comment by leinelissen** [comment]
Please let me know if you're still running into issues with this

**Comment by Mis1ify** [comment]
It's working, thx!
