### ISSUE TITLE
BUG: Unable to play .aif file (PCM_S16BE codec)

### ISSUE THREAD

**Issue by wildrun0** [leinelissen/jellyfin-audio-player#156]
Just figured out that I'm unable to play aif file. It shows radial progress bar and... do nothing

<img src="https://github.com/leinelissen/jellyfin-audio-player/assets/37260144/32c2eb80-ec8d-42aa-ae76-442c6691f9a4" width="264" height="572">

**Comment by leinelissen** [comment]
The progress indicator is shown because it tries to transcode the format (admittedly unsuccessfully). Proper transcoding support is on the way (tracked in #97), but requires a new minor Jellyfin release.

As for AIF, I need to do some checks with various codecs for support. I think iOS can play AIF files directly, but I have no direct evidence for this. Let me get back to you on this.

**Comment by leinelissen** [comment]
This should be fixed in v2.3.0, let me know if it works out for you.
