### ISSUE TITLE
Empty download list

### ISSUE THREAD

**Issue by mickeydarrenlau** [leinelissen/jellyfin-audio-player#166]
I have tons of downloads but all of them are blank items on the list

The Downloads work however.
![Screenshot_20230718_054523](https://github.com/leinelissen/jellyfin-audio-player/assets/62752664/71903b5b-76cc-4bc9-9813-68cc09a96a74)

**Comment by dbolger** [comment]
I'm able to reproduce this bug by downloading an album and clearing the Jellyfin cache within the app.

**Comment by leinelissen** [comment]
Do they show up again as soon as you view and load the respective albums?

**Comment by leinelissen** [comment]
Yeah this figures. Due to the way Fintunes is architected, the metadata of the tracks is stored separately from the audio file. This means when you delete the metadata cache, the file loses the data it's associated with. The metadata could be stored along with the audio file, but this also means keeping the two in sync, which I'm not a huge fan of. Some rearchitecturing might come in the future that syncs all tracks with Jellyfin at once, since there have been other problems as a result of this model.

Until then, I'll leave this issue open for people with a similar problem.

**Comment by mickeydarrenlau** [comment]
The file download from Jellyfin already contain the album data cz I embed all data into my music

**Comment by leinelissen** [comment]
That's true and it's an interesting technical solution. However, I'd like to leave all the metadata parsing for the different file formats to Jellyfin if possible. There's a whole minefield of different formats (ID3, Vorbis comments, iTunes tags, etc.) that requires tons of implementation, and they might mismatch whatever is in Jellyfin. If there is a more robust metadata cache, it will solve this problem, along with a host of other ones.
