### ISSUE TITLE
It simply doesn't work

### ISSUE THREAD

**Issue by HulkHogan6262** [leinelissen/jellyfin-audio-player#171]
Hello, I created this issue to inform you that the application does not work on my side. I can connect to my Jellyfin server without any problem but I can't see any titles and the search doesn't work.

### Server information :
Jellyfin 10.8.10
OS : Alpine Linux 3.18
Architecture: X64

### Customer information :
iPhone 8 Plus
iOS 16.5.1 (c)

I'm attaching screenshots / screen recordings here (yes, I'm French)

![2023-07-30 00_45_29-Tableau de bord et 18 pages de plus - Personnel – Microsoft​ Edge](https://github.com/leinelissen/jellyfin-audio-player/assets/93836385/6fea400f-ed05-4f44-b24d-5ad8375e0609)
![IMG_6492](https://github.com/leinelissen/jellyfin-audio-player/assets/93836385/7f5a1fdf-c80c-48fc-bfe5-cdff2fb65f1f)

https://github.com/leinelissen/jellyfin-audio-player/assets/93836385/192261d3-25a8-4a90-bb18-2042237a8558

https://github.com/leinelissen/jellyfin-audio-player/assets/93836385/daa84c94-939f-42a6-81f6-d6d44fbdf4ea

**Comment by leinelissen** [comment]
Hey @HulkHogan6262, thanks for reporting this and thanks for including the video! Just to get the obvious out of the way, are there any tracks listed in Jellyfin, and can you play them back from the regular interface?

**Comment by HulkHogan6262** [comment]
Yes, there are 116 tracks listed in Jellyfin and I can play them on the web interface.

**Comment by leinelissen** [comment]
Okay there might be something wrong in how the app tries to access your content. Would you mind creating an account for me on your Jellyfin server so I can take a look? You can DM me the credentials via the Discord server.

**Comment by leinelissen** [comment]
For others running into this in the future: the underlying issue was how music was categorised in Jellyfin. There's multiple ways of classifying audio when importing it in Jellyfin, but Fintunes only supports two ItemTypes currently: `MusicAlbum` and `Playlist`. If tracks are classified as `Audio`, Fintunes will be unable to retrieve them. 

An easy way to verify is to make sure that the tracks you want to listen to in Fintunes show up in the right places in Jellyfin. Navigate to your music library and check that these tracks appear under either the `Albums` tab or `Playlists` tab. 

This is a legacy problem that exists because Fintunes is originally album-focused. Some work is required before Fintunes can display lists of single tracks or list tracks by a single artists, for instance. Such work is tracked in https://github.com/leinelissen/jellyfin-audio-player/issues/70.
