### ISSUE TITLE
Doesn't seems to work with non https url

### ISSUE THREAD

**Issue by Morgan-6Freedom** [leinelissen/jellyfin-audio-player#205]
My server doesn't have https and when I put my link (http://my.server.com) to my server I have this error on ios ![image](https://github.com/leinelissen/jellyfin-audio-player/assets/49686866/0464a351-4155-4a42-a58a-ba503e27690a)

When I change my URL to https://my.server.com the message doesn't appear but I have a timeout error (expected because I don't have https)

It was working last time I entered the server URL. (I had a cache issue so I disconnected and now I'm stuck out of my server)

**Comment by Fangh** [comment]
Maybe it's linked to this : https://stackoverflow.com/questions/32631184/the-resource-could-not-be-loaded-because-the-app-transport-security-policy-requi

**Comment by lemonlimelabs** [comment]
This just started happening to me as well. It used to work in previous versions, I think something broke with the last update. For reference I've always used Tailscale as a VPN and it worked fine, but now I'm getting the same issue as OP.

**Comment by leinelissen** [comment]
Hey, this appears to be a regression after updating some dependencies. I'm incredibly sorry that happened. I'm releasing a hot fix for this right now, that should hit both stores asap. Thanks for reporting this!

**Comment by hpirila** [comment]
I am still getting this error in IOS. As per appstore the version is 2.3.1 and this should be fixed. Not sure how to check the version inside the app itself. Works with https, with http and port number in URL I get the same error.

**Comment by twhite96** [comment]
This is still an issue for me even after the hot fix.

**Comment by lemonlimelabs** [comment]
Same here still having the same issue on the newest app version.

**Comment by leinelissen** [comment]
Hey all, I did a little digging. As it turns out the App Transport Security settings are not additive but rather exclusionary. I left a setting in for local connections, and it ended up overriding the default one that allows HTTP for all origins. I'm releasing v2.3.2 now, which I've tested to be a definitive fix for these issues. They're in the queue for both TestFlight and the App Store and I expect at least one of those to be released in the next 24 hours. Incredibly sorry again for the regression! Thanks for all your patience and your continued usage of Fintunes!
