### ISSUE TITLE
The IOS-App crashes after Install

### ISSUE THREAD

**Issue by TaleOfThor** [leinelissen/jellyfin-audio-player#33]
The IOS-App crashes after Install.
If I try to open the App again, it keeps crashing.
I can't even see the Splash-Screen.
I sent you an Crash-Report via Testflight.

**Comment by leinelissen** [comment]
Hi there! Thanks for making the effort of coming on here and creating this issue. I have checked out your crash report that is in TestFlight, but it unfortunately lacks the details for me to get a grip on what is precisely going wrong. I will try and add some more comprehensive crash logging in a new version, probably in 1-2 weeks. I would then love to get back to you and figure out what's going wrong here.

Cheers,
Lei

**Comment by TaleOfThor** [comment]
Okay, thank you.
I will test the App again after you deployed the comprehensive crash logging.
Please let me know, when you publish the new version.

Cheers

**Comment by leinelissen** [comment]
Hi there! The last build released today includes the error logging. I'd love for you to try it out.

**Comment by TaleOfThor** [comment]
Hi! I tested the lates build and have send you the crash-report via testflight.

**Comment by yisiliang** [comment]
Crashes after Install too.
![image](https://user-images.githubusercontent.com/8147509/109411363-8a00b400-79dc-11eb-8454-f94f2794388a.png)

**Comment by leinelissen** [comment]
Hey there, sorry for not getting back to you earlier, this issue was somewhat difficult to investigate. In short, I was ultimately able to put Sentry error logging in, but it was weirdly not registering any errors from your crashes. This suggested that there was an error even before Sentry could be initialised.

What eventually tipped me off is that both of your have set languages that the app does not have any locales for. Because you don't have any fallback languages set (in General > Language and Region), no locale would be set at all and the app would crash. 

This error is now resolved, and the English locale should be popping up for both of you. I am building and releasing build 11 on TestFlight shortly, and I'd love to hear if this resolves your issues.

Cheers!

**Comment by yisiliang** [comment]
It's ok now. I can run it on my iPhone.

But I can't see my musics from the app. Does it support flac?

**Comment by leinelissen** [comment]
FLAC is supported, and regardless, your music should be visible in the application. Your music should be available to the account you use to log in, and it only supports albums for now. If there's anything you else you need supported I'll be happy to hear it.

**Comment by TaleOfThor** [comment]
The App now opens sucessfully. Even with System-Language set to "German".
I've found some other ossues with the App. I will open a seperate issue for that.
From my perspective, the issue can be closed.

**Comment by leinelissen** [comment]
Please do so, any feedback is duly appreciated!
