### ISSUE TITLE
ERR_CLEARTEXT_NOTE_PERMITTED

### ISSUE THREAD

**Issue by WhatSupQuebec** [leinelissen/jellyfin-audio-player#34]
![142252204_2768137383447721_3758061206588350321_n](https://user-images.githubusercontent.com/71474060/106311528-4c6d0780-6233-11eb-8eea-ba46d92a0f01.png)
When I try to connect the jellyfin music player to my server. I receive this error ERR_CLEARTEXT_NOTE_PERMITTED. My phone is a Google Pixel 2 XL. I try with another phone an iPhone 8 and it works. The error seems to be only for Android phones. Version of the apps i use is v0.0.1-alpha1

**Comment by WhatSupQuebec** [comment]
After one week i still have the same issue

**Comment by leinelissen** [comment]
Hi there @WhatSupQuebec !
Sorry for not getting back to you earlier, I was on a well-deserved holiday last week, and haven't been able to get to this earlier. As for your issue, it seems to be caused by Android not liking to connect to your HTTP server. I have changed a flag for the Android build, which I have just released as v0.1.0. Can you have a look and see if that improves things for you?

**Comment by WhatSupQuebec** [comment]
Thanks you for the fix all work
