### ISSUE TITLE
Opt out of Sentry logging

### ISSUE THREAD

**Issue by thornbill** [leinelissen/jellyfin-audio-player#35]
Would it be possible to add an option for users to opt out of the logging/tracking that was added in the latest release?

**Comment by leinelissen** [comment]
Hi @thornbill!
This is a reasonable request. In fact, I would like to make logging opt-in, but this requires some UI work, as well as some refactoring on the booting process. That will take some time. In the meantime, Build 7 remains available in Testflight, which does not include the Sentry SDK whatsoever. 

For some background context:
### Why the tracking?
Primarily to investigate issue #33 , but beyond this it is incredibly helpful in weeding out weird states and instances where data being passed around is not properly checked. In fact, two reports that have come in since enabling the logging have helped me quash two bugs involving rare states that could crash the application.

### Why is it not optional now?
Primarily because I was investigating a boot crash that the Testflight crash logs were not providing enough information for. Since in this instance the app was crashing on launch, making the logging opt-out would have made it impossible to debug the issue. 

### What data is gathered?

### Where is the data stored?
The Sentry backend is self-hosted on my own infrastructure. No-one but me has access to the servers, databases, application and data logs, least of all any Sentry staff. The infrastructure is hosted in the European Union. 

For convenience's sake, I will add this information to the README and hopefully the app at some point in the future. I hope this is all clear for now, and I will close this issue once all the above points are implemented.

**Comment by leinelissen** [comment]
Opt-in Sentry logging has just been release as build 10 on Testflight.
