### ISSUE TITLE
Download/playlist/flac support.

### ISSUE THREAD

**Issue by Bitwolfies** [leinelissen/jellyfin-audio-player#5]
Less of an issue just more wondering the progress of these features. feel free to close it.
I already love where this app is going, I just cant wait till these features are in, youve done an amazing job.

For downloads support if you dont have a way to implement it, a plex music app I used just used apples files app to download music so thats one way to do so.

Also the app Icon I would assume is temporary right? Just doesn't scream jellyfin.

Anyways, fantastic work, its just what jellyfin has needed, music is actually the last thing keeping my Plex server on. Hope all goes well with getting it onto testflight!

**Comment by leinelissen** [comment]
Hi there!

Thanks for your suggestions. Implementing download support should not be particularly difficult, most effort is probably in creating interfaces to manage what is downloaded so that it can be removed etc.

As for the app icon, I agree it's not particularly Jellyfin-inspired. It's mostly an excercise in making cool multi-layered shadows, but I am not married to it in any regard. 

Playlist support could probably be added based on Jellyfin, which would mean you would make the playlists in Jellyfin and could then play them in the app. 

As for the FLAC stuff, from what I can gather it seems to be supported by all moving parts. I would just need to make the selected codec into a setting. This should go hand in hand with allowing bitrate selection.

I'll slowly start work on some of these features and keep you in the loop when they are updated. Should be a lot easier when I do have TestFlight support though ;)

**Comment by UnbreakCode** [comment]
Any updates about flac support?

**Comment by leinelissen** [comment]
FLAC should be supported at this point. Would love to hear if you run into any issues

**Comment by UnbreakCode** [comment]
Well I'm currently using the latest TestFlight version and the flac file is not listed in the library for me.
I already resetted the cache and updated the library but still not visible for me

**Comment by leinelissen** [comment]
At the very least, the file should be visible in the app, as we don't apply any filtering on codec there. It might break on playing however. As a double-check: what kind of file/library are you playing from? We currently only query for `MusicAlbum` items form Jellyfin, so if your file is not part of an album, or sorted as an Ebook, it might not pop up ;)

**Comment by UnbreakCode** [comment]
Ok it's working if you have a full album

**Comment by leinelissen** [comment]
Ah right! When designing the application I made the implicit assumption that all music would be sorted by albums. Is there another use case that makes more sense for you?

**Comment by UnbreakCode** [comment]
My Library structe is like this:
Album -> Folder inside Library
Singles -> solo file inside library

Maybe it would be better if you can search in the whole library with the global search idk.

**Comment by dejan995** [comment]
Just to add to this.
FLAC files are not playing on the latest release v0.1.4.
I'm on Android 11.
The songs are displayed on the app but when I try to play them nothing happens.

**Comment by leinelissen** [comment]
Hmm, that's curious. I'll try and find out what's going wrong there...

**Comment by leinelissen** [comment]
The latest release (v0.2.2) includes support for both offline play/downloads and playlists. FLAC should be transcoded to AAC at this point. There are container formats that are lossless and play on Android and iOS natively (Ogg/FLAC and M4A/ALAC respectively), but Jellyfin doesn't allow transcoding to these containers as of yet. As soon as this support is present, FLACs should be able to be played natively.
