### ISSUE TITLE
Support For Downloads

### ISSUE THREAD

**Issue by TECHNETWORKINGSOLUTIONS** [leinelissen/jellyfin-audio-player#53]
Support for the download function and for it to work with the enable and disable downloading button in the admin dashboard for each client

And Also do you think it could work like for example Apple Music Where you can download music offline but there isn't really a physical file?

**Comment by leinelissen** [comment]
Download support has come up before, so that is being looked into ;). This would download the music file from Jellyfin and then store in the devices local storage. I'm not sure if that's what you mean regarding Apple Music, since the file that is downloaded won't be accessible other than through the app.

Also, what do you mean with a download button in the admin dashboard?

**Comment by TECHNETWORKINGSOLUTIONS** [comment]
Sorry for the late response but I've attached an image of what I mean about download enable or disable feature in the user configurator in jellyfins admin dashboard settings to control a user ability to download or not hopefully that made more sense .  Sorry for the confusion ![ image](https://user-images.githubusercontent.com/82411304/125684100-734edfb5-3800-47c1-8eea-d90f3d4866c2.png)

**Comment by leinelissen** [comment]
Ah right, that's interesting! I had no idea that option existed. We can probably respect it, but just as a FYI: technically speaking there is very little difference between streaming and downloading, so not sure if other apps will respect it as well.

**Comment by leinelissen** [comment]
Download support is included in the latest release: v0.2.2!
