### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by clothlust** [leinelissen/jellyfin-audio-player#72]
Hi there, thank you for this project, truly appreciate it! Just wondering if its possible to stream dsd files without down sampling it & is it possible to add support for an external dac?

Sorry if these questions sounds dumb, im kinda new to setting up a streaming server

**Comment by leinelissen** [comment]
Hi there! No worries at all, happy to help out. We are currently bound by the libraries we use to the playback formats that are natively supported by the OS (see for [Android](https://developer.android.com/guide/topics/media/media-formats#core) and [iOS](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/MultimediaPG/UsingAudio/UsingAudio.html)). As you can see DSD is not natively by any of those platforms, and hence we cannot support playing it back. If Jellyfin supports the transcoding, it will be transcoded to high-bitrate AAC, otherwise playback will fail.

As for the external DAC, this again is an issue for the OS. You can either connect an external DAC and if you are playing back a supported high-bitrate format, it should be picked up as such. You could also opt for AirPlay streaming to a DAC, which [supports lossless playback, but only up-to 48kHz/16-bit](https://discussions.apple.com/thread/252848734). 

You may need to mix and match formats for optimal results. I'm uneasy about the current situation (especially regarding FLAC), but supporting such formats with the current stack is infeasible so this is all I can do.
