### ISSUE TITLE
Add similar album or artist recommendations?

### ISSUE THREAD

**Issue by whydie100** [leinelissen/jellyfin-audio-player#73]
This is by far the best Jellyfin music player, but it’s missing this feature from Jellyfin. Possible to add it in? Thanks for the amazing app!

**Comment by leinelissen** [comment]
Hey there! Thanks for your feedback. This could be possible to implement, depending on the availability of an API for this data (shouldn't be a big problem). There is other stuff higher on the priority list right now, but if you're willing to submit a Pull Request I could give you some pointers with regards to implementation ;).

**Comment by rtakehara** [comment]
Last.fm provides an API, that’s an option I think

**Comment by leinelissen** [comment]
There is [an API in Jellyfin](https://api.jellyfin.org/#tag/Suggestions/operation/GetSuggestions) already that generates suggestions for a particular media item. This is something that looks quite straightforward to implement. Again, if anyone needs pointers how to get started on it, please get in touch!

**Comment by leinelissen** [comment]
This is implemented in v2.1.0!

**Comment by sortedcord** [comment]
Hi, sorry to bring this in again, not sure whether to make a new for this, but will it be possible to support 3rd party APIs for recommendations? I'm currently brainstorming a project related to generating recommendations it will be awesome if it this client (or jellyfin) is able to support it...

**Comment by leinelissen** [comment]
I would strongly prefer the recommendations to come from Jellyfin, so that there is only one datasource for the app. It's possible to create plugins for Jellyfin that might hook into the recommendation logic. 

If a third party API is the only way to do it and there is strong support for the username, I would consider merging an implementation for it. But it would need strong privacy guarantees, easy setup and a de facto standard for it.
