### ISSUE TITLE
Track progress missing

### ISSUE THREAD

**Issue by PauFCB** [leinelissen/jellyfin-audio-player#88]
Hi, when I close and reopen the app, there is no song and the now playing section disappear, wold be nice that the app remember when we left the song before closing. Also I can't add any song to a playlist, I have to do it on the web browser. thanks (iOS TestFlight)

**Comment by leinelissen** [comment]
Hi @PauFCB! With closing the app, do you mean switching to another app or do you mean going to the app overview and forcefully closing the app? As per Apple (https://support.apple.com/en-gb/HT201330) forcefully closing the app is meant to reset it, in case the app becomes unresponsive or reaches an unknown state. After pausing a song and leaving the app for some time, iOS may also forcefully close apps in order to free memory. I don't consider this problematic behaviour currently.

As for adding songs to playlists, this would be a nice feature, but I am unlikely to implement it anytime soon, so making playlists in Jellyfin is the recommended way forward for now.

**Comment by PauFCB** [comment]
Yes, I mean manually close swiping up. And for the playlists, I will do this way, adding manually one by one on the Mac web version and in the mobile app downloading the whole playlist. I hope in the future we can do this without leaving the mobile app!
I’m curious, what are you planing next for the app? I really like, seems like the official Music ios app but without all the streaming noise.
Thanks !

**Comment by leinelissen** [comment]
I am currently working on getting this app on the App Store and play store, and that should take a decent amount of time. After that, I'll be weighing a lot of feature requests and going at them one by one. There isn't necessarily a grand plan there, but I want to look at CarPlay support, getting the audio engine to accept more formats and so forth.
